### ISSUE TITLE
Ignores parallelConnections config

### ISSUE THREAD

**Issue by ghost** [KararTY/dank-twitch-irc#9]
The bot gets rate limited after joing over 20 channels even with a custom config like:

`connectionRateLimits: {
				parallelConnections: 1, // 1 by default
				// time to wait after each connection before a new connection can begin
				releaseTime: 2000, // in milliseconds, 2 seconds by default
			  }`

It shouldn't get a rate limit with this settings as on twtich docs https://dev.twitch.tv/docs/irc/ 

20 authentication attempts per 10 seconds per user.
20 join attempts per 10 seconds per user.

**Comment by KararTY** [comment]
<details>
<summary> Old text </summary>

Thank you for reporting the issue, I checked this and the problem lies with `maxChannelCountPerConnection` being set to 90 as default.

You can fix this by adding `maxChannelCountPerConnection: 20` to your ChatClient object.

```js
const client = new ChatClient({
	// ...
	maxChannelCountPerConnection: 20,
	// ...
	connectionRateLimits: {
		parallelConnections: 5,
		releaseTime: 2000,
	},
});
```

Please report back if that fixes it for you and I'll open up a PR to fix it.

</details>

Looking at this issue more thoroughly, I did see issues with join and joinAll not properly respecting the ratelimits. I'll take a look at it, thanks for reporting the problem.
